version: '2'
services:
  web:
    image: odoo:15
    depends_on:
      - postgres-12
    ports:
      - "2515:8069"   # ganti port biar tidak bentrok dengan Odoo 14 (kalau masih jalan)
    volumes:
      - odoo-data-volume:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    environment:
      - PASSWORD_FILE=/run/secrets/postgresql_password
    secrets:
      - postgresql_password

  postgres-12:
    image: postgres:12
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgresql_password
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db-data-volume:/var/lib/postgresql/data/pgdata
    secrets:
      - postgresql_password

volumes:
  odoo-data-volume:
  db-data-volume:

secrets:
  postgresql_password:
    file: ./config/odoo_pg_pass
